trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: yourjavafunctionname
  serviceConnectionToAzure: connection-to-yourjavafunctionname

steps:
- script: |
    echo 'appName:                         '$(appName)
    echo 'serviceConnectionToAzure:        '$(serviceConnectionToAzure)
    echo 'system.defaultworkingdirectory:  '$(system.defaultworkingdirectory)
    echo 'build.artifactstagingdirectory:  '$(build.artifactstagingdirectory)
  displayName: 'display the pipeline variables'
  condition: always()

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)    

- script: ls -alR
  displayName: 'list files'
  condition: always()

- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: functionApp
    appName: $(appName)
    package: $(build.artifactstagingdirectory)/$(appName)
    
